name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"      # every day at midnight UTC
  workflow_dispatch:          # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: hasan-kal
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸš€ Publish Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}